#!/bin/bash
etags \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/context/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/context/configuration.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/context/model_context.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/core/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/core/db.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/core/errors.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/core/log.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/core/form/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/core/form/abstract_form.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/core/form/fields.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/constants.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/integrand_mappings.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/dismod_extractor.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/dismod_filler.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/dismod_io.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/dismod_sqlite.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/run_dismod.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/table_metadata.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/fill_extract_helpers/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/fill_extract_helpers/data_tables.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/fill_extract_helpers/grid_tables.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/fill_extract_helpers/posterior_to_prior.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/fill_extract_helpers/reference_tables.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/dismod/api/fill_extract_helpers/utils.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/executor/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/executor/configure_inputs.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/executor/dismod_db.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/executor/args/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/executor/args/arg_utils.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/executor/args/args.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/executor/utils/utils.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/asdr.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/base_input.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/covariate_data.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/covariate_specs.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/csmr.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/data.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/demographics.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/locations.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/measurement_inputs.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/population.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/uncertainty.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/utilities/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/utilities/covariate_specifications.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/utilities/covariate_weighting.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/utilities/data.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/utilities/gbd_ids.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/utilities/reduce_data_volume.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/inputs/utilities/transformations.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/age_time_grid.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/covariate.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/dismod_groups.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/grid_alchemy.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/model.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/priors.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/smooth_grid.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/var.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/utilities/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/model/utilities/grid_helpers.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/saver/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/saver/results_handler.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/settings/__init__.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/settings/convert.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/settings/settings.py \
    /Users/gma/Projects/IHME/GIT/at_ihme.git/src/cascade_at/settings/settings_config.py
